module.exports = {
  apps: [
    {
      name: 'tnt-siprec-proxy',
      script: 'packages/siprec-proxy/dist/index.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        SIPREC_PORT: 5060,
        WS_PORT: 3001,
      },
      error_file: './logs/siprec-proxy-error.log',
      out_file: './logs/siprec-proxy-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'tnt-transcription',
      script: 'packages/transcription/dist/index.js',
      cwd: __dirname,
      instances: 2, // Run 2 instances for load balancing
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        WHISPER_MODEL: 'base',
        API_PORT: 3002,
      },
      error_file: './logs/transcription-error.log',
      out_file: './logs/transcription-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '2G',
    },
    {
      name: 'tnt-ui-server',
      script: 'serve',
      args: '-s packages/ui/dist -l 5173',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/ui-error.log',
      out_file: './logs/ui-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
    },
  ],
};
